export enum QueryKeys {
  PRODUCTS = "products",
  PRODUCT = "product",
  CATEGORIES = "categories",
  CATEGORY = "category",
  CART = "cart",
  CART_ITEMS = "cart-items",
  CHECKOUT = "checkout",
  ORDERS = "orders",
  ORDER = "order",
  USER = "user",
  USERS = "users",
  ADDRESSES = "addresses",
  ADDRESS = "address",
  DELIVERY_ZONES = "delivery-zones",
  DELIVERY_ZONE = "delivery-zone",
  RESTAURANTS = "restaurants",
  RESTAURANT = "restaurant",
}